Repository ros-infrastructure/roswiki, pull requests merged in 2018-05, with the labels that each got.

#247 remove Jade from distro_names_buildfarm now that it's EOL
  macro/macroutils.py
Labels: in progress

#204 Hide eol distros
  custom/js/rosversion.js
  macro/PackageHeader.py
  macro/StackHeader.py
  macro/Version.py
  macro/headers.py
  macro/macroutils.py
Labels: enhancement, in review

#246 Extend 'Continuous Integration' badge with dev job test stats.
  macro/headers.py
  macro/macroutils.py
Labels: enhancement
